USE INTEL_SMART_ANTENNA_DATA_LIVERMORE;
DELIMITER $$
CREATE PROCEDURE `AlgorithmsPredictionAccuracyResults`(IN PARAM_CORELATION_ID VARCHAR(45))
BEGIN

insert into PREDICTION_ACCURACY_RESULT 
 SELECT CORELATION_ID,'Clothgrouping', ZONE_ACCURACY,SUBQUADRANT_ACCURACY,
QUADRANT_ACCURACY 
FROM CLOTHGROUPING_ACCURACY_RESULT 
where CORELATION_ID=PARAM_CORELATION_ID;

insert into PREDICTION_ACCURACY_RESULT 
 SELECT CORELATION_ID,'J48', ZONE_ACCURACY,SUBQUADRANT_ACCURACY,
QUADRANT_ACCURACY 
FROM J48_ACCURACY_RESULT 
where CORELATION_ID=PARAM_CORELATION_ID;

insert into PREDICTION_ACCURACY_RESULT 
 SELECT CORELATION_ID,'RandomForest', ZONE_ACCURACY,SUBQUADRANT_ACCURACY,
QUADRANT_ACCURACY 
FROM RANDOM_FOREST_BINARY_ACCURACY_RESULT  
where CORELATION_ID=PARAM_CORELATION_ID;

insert into PREDICTION_ACCURACY_RESULT 
 SELECT CORELATION_ID,'VotingLogic', ZONE_ACCURACY,SUBQUADRANT_ACCURACY,
QUADRANT_ACCURACY 
FROM VOTING_ACCURACY_RESULT 
where CORELATION_ID=PARAM_CORELATION_ID;

END$$
DELIMITER ;
