
CREATE DATABASE `INTEL_SMART_ANTENNA_DATA_STORE_PLAZA` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE INTEL_SMART_ANTENNA_DATA_STORE_PLAZA;

CREATE TABLE `CLOTHGROUPING_ACCURACY_RESULT` (
  `CORELATION_ID` varchar(45) NOT NULL,
  `TOTAL_UNIQUE_TAGS` int(11) NOT NULL,
  `PREDICTED_SUCCESS_ZONE_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_ZONE_COUNT` int(11) NOT NULL,
  `ZONE_ACCURACY` double NOT NULL,
  `PREDICTED_SUCCESS_SUBQUADRANT_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_SUBQUADRANT_COUNT` int(11) NOT NULL,
  `SUBQUADRANT_ACCURACY` double NOT NULL,
  `PREDICTED_SUCCESS_QUADRANT_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_QUADRANT_COUNT` int(11) NOT NULL,
  `QUADRANT_ACCURACY` double NOT NULL,
  `TOTAL_TAGS` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CLOTHGROUPING_RESULT` (
  `EPC` varchar(45) NOT NULL,
  `PredictedShelf` varchar(45) NOT NULL,
  `PredictedZone` varchar(45) NOT NULL,
  `PredictedSubQuadrant` varchar(45) NOT NULL,
  `PredictedQuadrant` varchar(45) NOT NULL,
  `CORELATION_ID` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `J48_ACCURACY_RESULT` (
  `CORELATION_ID` varchar(45) NOT NULL,
  `TOTAL_UNIQUE_TAGS` int(11) NOT NULL,
  `PREDICTED_SUCCESS_ZONE_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_ZONE_COUNT` int(11) NOT NULL,
  `ZONE_ACCURACY` double NOT NULL,
  `PREDICTED_SUCCESS_SUBQUADRANT_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_SUBQUADRANT_COUNT` int(11) NOT NULL,
  `SUBQUADRANT_ACCURACY` double NOT NULL,
  `PREDICTED_SUCCESS_QUADRANT_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_QUADRANT_COUNT` int(11) NOT NULL,
  `QUADRANT_ACCURACY` double NOT NULL,
  `TOTAL_TAGS` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `J48_RESULT` (
  `EPC` varchar(45) NOT NULL,
  `PredictedShelf` varchar(45) NOT NULL,
  `PredictedZone` varchar(45) NOT NULL,
  `PredictedSubQuadrant` varchar(45) NOT NULL,
  `PredictedQuadrant` varchar(45) NOT NULL,
  `CORELATION_ID` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PREDICTION_ACCURACY_RESULT` (
  `CORELATION_ID` varchar(45) NOT NULL,
  `ALGORITHM` varchar(45) NOT NULL,
  `ZONE_ACCURACY` double NOT NULL,
  `SUBQUADRANT_ACCURACY` double NOT NULL,
  `QUADRANT_ACCURACY` double NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PREDICTION_RESULT` (
  `EPC` varchar(45) NOT NULL,
  `EXPECTED_SHELF` varchar(45) NOT NULL,
  `CG_PREDICTED_SHELF` varchar(45) NOT NULL,
  `J48_PREDICTED_SHELF` varchar(45) NOT NULL,
  `RF_PREDICTED_SHELF` varchar(45) NOT NULL,
  `VOTING_PREDICTED_SHELF` varchar(45) NOT NULL,
  `EXPECTED_SUBQUADRANT` varchar(45) NOT NULL,
  `CG_PREDICTED_SUBQUADRANT` varchar(45) NOT NULL,
  `J48_PREDICTED_SUBQUADRANT` varchar(45) NOT NULL,
  `RF_PREDICTED_SUBQUADRANT` varchar(45) NOT NULL,
  `VOTING_PREDICTED_SUBQUADRANT` varchar(45) NOT NULL,
  `EXPECTED_QUADRANT` varchar(45) NOT NULL,
  `CG_PREDICTED_QUADRANT` varchar(45) NOT NULL,
  `J48_PREDICTED_QUADRANT` varchar(45) NOT NULL,
  `RF_PREDICTED_QUADRANT` varchar(45) NOT NULL,
  `VOTING_PREDICTED_QUADRANT` varchar(45) NOT NULL,
  `CORELATION_ID` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `RANDOM_FOREST_BINARY_ACCURACY_RESULT` (
  `CORELATION_ID` varchar(45) NOT NULL,
  `TOTAL_UNIQUE_TAGS` int(11) NOT NULL,
  `PREDICTED_SUCCESS_ZONE_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_ZONE_COUNT` int(11) NOT NULL,
  `ZONE_ACCURACY` double NOT NULL,
  `PREDICTED_SUCCESS_SUBQUADRANT_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_SUBQUADRANT_COUNT` int(11) NOT NULL,
  `SUBQUADRANT_ACCURACY` double NOT NULL,
  `PREDICTED_SUCCESS_QUADRANT_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_QUADRANT_COUNT` int(11) NOT NULL,
  `QUADRANT_ACCURACY` double NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `RANDOM_FOREST_BINARY_RESULT` (
  `EPC` varchar(45) NOT NULL,
  `PredictedShelf` varchar(100) NOT NULL,
  `PredictedCount` int(11) NOT NULL,
  `PredictedZone` varchar(45) NOT NULL,
  `PredictedSubQuadrant` varchar(45) NOT NULL,
  `PredictedQuadrant` varchar(45) NOT NULL,
  `CORELATION_ID` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TAGREADEVENTS` (
  `EPC` varchar(45) NOT NULL,
  `RSSI` double NOT NULL,
  `READER_ID` varchar(45) NOT NULL,
  `ANTENNA_ID` varchar(45) NOT NULL,
  `PHASE` double NOT NULL,
  `FREQUENCY` double NOT NULL,
  `CAPTURE_TIME` varchar(45) NOT NULL,
  `RSSI_MW` double NOT NULL,
  `CORELATION_ID` varchar(45) NOT NULL,
  KEY `epcIndex` (`EPC`),
  KEY `phaseIndex` (`PHASE`),
  KEY `rssiIndex` (`RSSI`),
  KEY `frequencyIndex` (`FREQUENCY`),
  KEY `antennaIndex` (`ANTENNA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `VOTING_ACCURACY_RESULT` (
  `CORELATION_ID` varchar(45) NOT NULL,
  `TOTAL_UNIQUE_TAGS` int(11) NOT NULL,
  `PREDICTED_SUCCESS_ZONE_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_ZONE_COUNT` int(11) NOT NULL,
  `ZONE_ACCURACY` double NOT NULL,
  `PREDICTED_SUCCESS_SUBQUADRANT_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_SUBQUADRANT_COUNT` int(11) NOT NULL,
  `SUBQUADRANT_ACCURACY` double NOT NULL,
  `PREDICTED_SUCCESS_QUADRANT_COUNT` int(11) NOT NULL,
  `PREDICTED_FAILURE_QUADRANT_COUNT` int(11) NOT NULL,
  `QUADRANT_ACCURACY` double NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `VOTING_RESULT` (
  `EPC` varchar(45) NOT NULL,
  `PredictedShelf` varchar(45) NOT NULL,
  `PredictedZone` varchar(45) NOT NULL,
  `PredictedSubQuadrant` varchar(45) NOT NULL,
  `PredictedQuadrant` varchar(45) NOT NULL,
  `CORELATION_ID` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CLOTHGROUPING_MOVED_TAGS_RESULT` (
  `EPC` varchar(45) NOT NULL,
  `MovedShelf` varchar(45) NOT NULL,
  `CORELATION_ID` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SUB_QUADRANT_WISE_PREDICTION_RESULT` (
  `EPC` varchar(45) NOT NULL,
  `EXPECTED_SQ` int(11) NOT NULL,
  `PREDICTED_SQ_BY_CG_RF_J48` int(11) NOT NULL,
  `PREDICTED_SQ_BY_CG_RF` int(11) NOT NULL,
  `PREDICTED_SQ_BY_CG_J48` int(11) NOT NULL,
  `PREDICTED_SQ_BY_RF_J48` int(11) NOT NULL,
  `PREDICTED_SQ_BY_CG` int(11) NOT NULL,
  `PREDICTED_SQ_BY_RF` int(11) NOT NULL,
  `PREDICTED_SQ_BY_J48` int(11) NOT NULL,
  `CORELATION_ID` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `REFERENCE_TABLE_PLAZA` (
  `EPC` varchar(30) NOT NULL,
  `Quadrant` varchar(10) NOT NULL,
  `SubQuadrant` varchar(10) NOT NULL,
  `Zone` varchar(10) NOT NULL,
  `Shelf` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



