USE INTEL_SMART_ANTENNA_DATA_STORE_PLAZA;

DELIMITER $$
CREATE  PROCEDURE `AlgorithmsPredictionResults`(IN PARAM_CORELATION_ID VARCHAR(45), IN PARAM_REF_TABLE_NAME VARCHAR(100))
BEGIN

INSERT INTO PREDICTION_RESULT
	SELECT reference.EPC, reference.Shelf as SHELF,
	IFNULL((SELECT PredictedShelf FROM CLOTHGROUPING_RESULT 
as result where CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') 
as CG_PREDICTED_SHELF, 
	IFNULL((SELECT PredictedShelf FROM J48_RESULT as result where
 CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') as J48_PREDICTED_SHELF, 
	IFNULL((SELECT PredictedShelf FROM RANDOM_FOREST_BINARY_RESULT as result where
 CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') as RF_PREDICTED_SHELF,
	IFNULL((SELECT PredictedShelf FROM VOTING_RESULT as result where 
CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') as VOTING_PREDICTED_SHELF,
reference.SubQuadrant,
IFNULL((SELECT PredictedSubQuadrant FROM CLOTHGROUPING_RESULT 
as result where CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') 
as CG_PREDICTED_SubQuadrant,
	IFNULL((SELECT PredictedSubQuadrant FROM J48_RESULT as result where
 CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') as J48_PREDICTED_SubQuadrant, 
	IFNULL((SELECT PredictedSubQuadrant FROM RANDOM_FOREST_BINARY_RESULT as result where
 CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') as RF_PREDICTED_SubQuadrant,
	IFNULL((SELECT PredictedSubQuadrant FROM VOTING_RESULT as result where 
CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') as VOTING_PREDICTED_SubQuadrant,
reference.Quadrant,
IFNULL((SELECT PredictedQuadrant FROM CLOTHGROUPING_RESULT 
as result where CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') 
as CG_PREDICTED_Quadrant,
	IFNULL((SELECT PredictedQuadrant FROM J48_RESULT as result where
 CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') as J48_PREDICTED_Quadrant, 
	IFNULL((SELECT PredictedQuadrant FROM RANDOM_FOREST_BINARY_RESULT as result where
 CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') as RF_PREDICTED_Quadrant,
	IFNULL((SELECT PredictedQuadrant FROM VOTING_RESULT as result where 
CORELATION_ID=PARAM_CORELATION_ID and result.EPC=reference.epc),'Not Predeicted') 
as VOTING_PREDICTED_Quadrant,PARAM_CORELATION_ID
 FROM  REFERENCE_TABLE_PLAZA reference where reference.EPC 
	in (select distinct epc from CLOTHGROUPING_RESULT 
where CORELATION_ID=PARAM_CORELATION_ID);

END$$
DELIMITER ;

DELIMITER $$
CREATE  PROCEDURE `AlgorithmsPredictionAccuracyResults`(IN PARAM_CORELATION_ID VARCHAR(45))
BEGIN
insert into  PREDICTION_ACCURACY_RESULT 
 SELECT CORELATION_ID,'Clothgrouping', ZONE_ACCURACY,SUBQUADRANT_ACCURACY,
QUADRANT_ACCURACY 
FROM INTEL_SMART_ANTENNA_DATA_STORE_PLAZA.CLOTHGROUPING_ACCURACY_RESULT 
where CORELATION_ID=PARAM_CORELATION_ID;


insert into  PREDICTION_ACCURACY_RESULT 
 SELECT CORELATION_ID,'J48', ZONE_ACCURACY,SUBQUADRANT_ACCURACY,
QUADRANT_ACCURACY 
FROM INTEL_SMART_ANTENNA_DATA_STORE_PLAZA.J48_ACCURACY_RESULT 
where CORELATION_ID=PARAM_CORELATION_ID;

insert into  PREDICTION_ACCURACY_RESULT 
 SELECT CORELATION_ID,'RandomForest', ZONE_ACCURACY,SUBQUADRANT_ACCURACY,
QUADRANT_ACCURACY 
FROM INTEL_SMART_ANTENNA_DATA_STORE_PLAZA.RANDOM_FOREST_BINARY_ACCURACY_RESULT  
where CORELATION_ID=PARAM_CORELATION_ID;


insert into  PREDICTION_ACCURACY_RESULT 
 SELECT CORELATION_ID,'VotingLogic', ZONE_ACCURACY,SUBQUADRANT_ACCURACY,
QUADRANT_ACCURACY 
FROM INTEL_SMART_ANTENNA_DATA_STORE_PLAZA.VOTING_ACCURACY_RESULT 
where CORELATION_ID=PARAM_CORELATION_ID;

END$$
DELIMITER ;

